---
profile: test_aiida
email: aiida@localhost
first_name: Giuseppe
last_name: Verdi
institution: Khedivial
db_backend: core.psql_dos
db_engine: postgresql_psycopg2
db_host: localhost
db_port: 5432
db_name: test_aiida
db_username: postgres
db_password: ''
broker_protocol: amqp
broker_username: guest
broker_password: guest
broker_host: 127.0.0.1
broker_port: 5672
broker_virtual_host: ''
repository: /tmp/test_repository_test_aiida/
test_profile: true
