# when we run locally, we must first create a docker container
# then we run the playbooks inside that

scenario:
  create_sequence:
    - create
    - prepare
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
# configuration for building the isolated container
driver:
  name: docker
platforms:
- name: molecule-aiida-${AIIDA_TEST_BACKEND:-psql_dos}
  image: molecule_tests
  context: "../.."
  command: /sbin/my_init
  healthcheck:
    test: wait-for-services
  volumes:
  - molecule-pip-cache-${AIIDA_TEST_BACKEND:-psql_dos}:/home/.cache/pip
  privileged: true
  retries: 3
# configuration for how to run the playbooks
provisioner:
  name: ansible
  # log: true  # for debugging
  playbooks:
    create: create_docker.yml
    prepare: setup_python.yml
    converge: setup_aiida.yml
    verify: run_tests.yml
  config_options:
    defaults:
      # nicer stdout printing
      stdout_callback: yaml
      bin_ansible_callbacks: true
      # add timing to tasks
      callback_whitelist: timer, profile_tasks
      # reduce CPU load
      internal_poll_interval: 0.002
    ssh_connection:
      # reduce network operations
      pipelining: True
  inventory:
    hosts:
      all:
        vars:
          become_method: su
          aiida_user: aiida
          aiida_core_dir: /aiida-core
          aiida_pip_cache: /home/.cache/pip
          venv_bin: /opt/conda/bin
          ansible_python_interpreter: "{{ venv_bin }}/python"
          aiida_backend: ${AIIDA_TEST_BACKEND:-core.psql_dos}
          aiida_workers: ${AIIDA_TEST_WORKERS:-2}
          aiida_path: /tmp/.aiida_${AIIDA_TEST_BACKEND:-psql_dos}
          aiida_query_stats: true
